FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY analysis-service/ ./analysis-service/
COPY detection-engine/ ./detection-engine/
COPY alert-service/ ./alert-service/
COPY ml-models/saved/ ./ml-models/saved/
COPY .env* ./

CMD ["python", "analysis-service/analyzer.py"]
