FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY analysis_service/ ./analysis_service/
COPY detection_engine/ ./detection_engine/
COPY alert_service/ ./alert_service/
COPY ml-models/saved/ ./ml-models/saved/

CMD ["python", "analysis_service/analyzer.py"]
